<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/css/reset.css" type="text/css" rel="stylesheet" />
<link href="/css/admin.css" type="text/css" rel="stylesheet" />
<script src="/Javascript/jquery-1.9.1.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="/css/tab.css" />
<title>项目权限列表</title>
<script type="text/javascript">
 function btnsel()
 {
	 var selname=document.getElementById('selname').value;
	 window.location.href="/Projects/projectlst?selname="+selname;
 }
</script> 
</head>
<body >
<div style="width:1520px;height:600px;">
 <?php require APPLICATION_PATH.'/views/scripts/adminlogin/head.phtml';?>  
<div style="float:left;">
  <?php require APPLICATION_PATH.'/views/scripts/adminlogin/left.phtml';?>         
</div>
<div class="clear:both;"></div>
<div style="float:left;background:#F0F8FF;width:87.4%;height:900px;" >
<table>
<tr>
<td height="30" >&nbsp;&nbsp;当前位置：<b>权限管理--权限列表</b></td>
<td height="30">
	<div style="margin-left:250px;">
	关键字搜索：<input type="text" id="selname" name="selname" style="width:200px;height:25px;color:gray;font-size:13px;" value="<?php echo $this->selname==NULL?'项目名称/用户':$this->selname?>" onclick="if(this.value=='项目名称/用户'){this.value='';}" onblur="if(this.value==''){this.value='项目名称/用户'}"/>
	 <input type="button" onclick="btnsel();" value="GO"/>
	</div>
</td>
</tr>
</table>
<hr />
<div style="width:985px;height:40px;line-height:40px;margin-left:50px;font-size:18px;font-weight:bold;color:#0B54AD;">权限列表(<?=count($this->competencelst)?>)</div>
<br/>
<div style="font-size: 14px">       
 <table class="mm" style="width:70%; margin:0 auto;">
  <tr>
  <th>用户名</th><th>密码</th><th>可见项目</th><th>操作</th>
  </tr>
  <?php foreach($this->competencelst as $competence){?>
  <tr>
  <td><?=$competence['Medi_UserName']?></td>
  <td><?=$competence['Medi_TruePwd']?></td>
  <td><?=$competence['Medi_ProjectName']?></td>
 <td><a href="/Projects/competencedit?competenceid=<?=$competence['Medi_CompetenceID']?>&edittype=1">编辑</a>&nbsp;&nbsp;&nbsp;&nbsp;<a onclick="return confirm('确实要删除这个用户权限么？')" href="/Projects/competencedel?competenceid=<?=$competence['Medi_CompetenceID']?>">删除</a></td>
  </tr>
  <?php }?>
   </table> 
  <div style="padding-top:10px;margin-left:200px;"><?=$this->result?></div>
</div>
<div class="clear:both;"></div>
</div>
</div>
</body>
</html>
