<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/css/reset.css" type="text/css" rel="stylesheet" />
<link href="/css/admin.css" type="text/css" rel="stylesheet" />
<script src="/Javascript/jquery-1.9.1.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="/css/tab.css" />
<title>添加数据库字典</title>
<style type="text/css">
.btn{ background-color:#FFF; border:1px solid #CDCDCD;height:30px; width:70px;} 
</style>
<script type="text/javascript">
function check()
{
	var name=document.getElementById("dataname").value;
	if(name==""){
		alert("请输入数据库字典名称");
		return false;
	}
}
</script>
</head>
<body >
<div style="width:1520px;height:600px;">
 <?php require APPLICATION_PATH.'/views/scripts/adminlogin/head.phtml';?>  
<div style="float:left;">
  <?php require APPLICATION_PATH.'/views/scripts/adminlogin/left.phtml';?>         
</div>
<div class="clear:both;"></div>
<div style="float:left;background:#F0F8FF;width:87.4%;height:900px;" >
<table>
<tr>
<td height="30" >&nbsp;&nbsp;当前位置：<b><?=$this->projectname?>项目--添加数据库字典</b></td>
</tr>
</table>
<hr />
<br/><br/>
<div style="font-size: 14px">  
<form action="/Data/savenewdata" method="post">  
<input type="hidden" name="proid" value="<?=$this->projectid?>"></input>
<input type="hidden" name="proname" value="<?=$this->projectname?>"></input>
 <table class="mm" style="width:40%; margin:0 auto;">
 <tr style="height:30px;"><td>数据库字典名称</td>
 	<td><input type="text" id="dataname" name="dataname" value="" style="width:300px;height:25px;"></input></td>
 </tr>
 <tr style="height:50px;"><td>所属项目</td>
 	<td><?=$this->projectname?></td>
 </tr>
 <tr><td colspan="2"><input type="submit" name="submit" value="保存" class="btn" onclick="return check();"></input>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 <input type="button" name="cancel" value="取消" class="btn" onclick="window.location.href='/Data/datalst?projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>';"></input></td></tr>
   </table> 
   </form> 
</div>
<div class="clear:both;"></div>
</div>
</div>
</body>
</html>

