<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/css/reset.css" type="text/css" rel="stylesheet" />
<link href="/css/admin.css" type="text/css" rel="stylesheet" />
<script src="/Javascript/jquery-1.9.1.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="/css/tab.css" />
<title>数据表信息</title>
<style type="text/css">
.td
{
	 text-align:right;
}
.btn{ background-color:#FFF; border:1px solid #CDCDCD;height:30px; width:70px;} 
</style>
</head>
<body>
<div style="width:1520px;height:600px;">
 <?php require APPLICATION_PATH.'/views/scripts/adminlogin/head.phtml';?>  
<div style="float:left;">
  <?php require APPLICATION_PATH.'/views/scripts/adminlogin/left.phtml';?>         
</div>
<div class="clear:both;"></div>
<div style="float:left;background:#F0F8FF;width:87.4%;height:auto;" >
<table>
<tr>
<td height="30" >&nbsp;&nbsp;&nbsp;&nbsp;当前位置：<b>
<a href="/Data/tablelst?dataid=<?=$this->dataid?>&projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>"><?=$this->dataname?></a>--<?=$this->detail['Medi_TableName']==""?"添加数据表":$this->detail['Medi_TableName']?></b></td>
</tr>
</table>
<hr />
<br/>
<div style="font-size: 14px"> 
 <table class="mm" style="width:90%;">
 <tr>
 <td class="td" style="width:10%;">数据表名称&nbsp;&nbsp;</td>
 <td colspan="3"><?=$this->detail['Medi_TableName']?></td>
 </tr>
 <tr>
 <td class="td">编写人&nbsp;&nbsp;</td>
 <td><?=$this->detail['Medi_TableCreatName']?></td>
 <td class="td">创建时间&nbsp;&nbsp;</td>
 <td><?=$this->detail['Medi_TableCreatTime']?></td>
 </tr>
  <tr>
 <td class="td">修改人&nbsp;&nbsp;</td>
 <td><?=$this->detail['Medi_TableUpdateName']?></td>
 <td class="td">修改时间&nbsp;&nbsp;</td>
 <td><?=$this->detail['Medi_TableUpdateTime']?></td>
 </tr>
  <tr>
 <td class="td">数据表说明&nbsp;&nbsp;</td>
 <td colspan="3" class="td2"><?=$this->detail['Medi_TableNote']?></td>
 </tr>
  <tr>
 <td class="td">表内字段信息&nbsp;&nbsp;</td>
 <td colspan="3">
	 <table style="width:95%;margin-left:20px;" id="fieldtable">
	 <tr>
	 <td>字段名</td><td>字段类型</td><td>字段长度</td><td>标识</td><td>主键</td><td>是否允许空</td><td>说明</td>
	 </tr>
	 <?php foreach ($this->fields as $fields ){?>
	 <tr>
	 <td><?=$fields['Medi_DataName']?></td>
	 <td><?=$fields['Medi_DataType']?></td>
	 <td><?=$fields['Medi_DataLength']?></td>
	 <td><?php echo $fields['Medi_IsSign']==1?"是":"否"?></td>
	 <td><?php echo $fields['Medi_IsPrimary']==1?"是":"否"?></td>
	 <td><?php echo $fields['Medi_IsEmpty']==1?"是":"否"?></td>
	 <td style="text-align:left;padding-left:10px;"><?=$fields['Medi_DataNote']?></td>
	 </tr>
	 <?php }?>
	  </table>
 </td>
 </tr>
 <tr>
 <td colspan="4"><input type="button" class="btn" value="返回" onclick="window.location.href='/Data/tablelst?dataid=<?=$this->dataid?>&projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>';"></input></td>
 </tr>
 </table> 
</div>
<div class="clear:both;"></div>
</div>
</div>
</body>
</html>
