<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/css/reset.css" type="text/css" rel="stylesheet" />
<link href="/css/admin.css" type="text/css" rel="stylesheet" />
<script src="/Javascript/jquery-1.9.1.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="/css/tab.css" />
<title>数据表信息</title>
<style type="text/css">
.td
{
	 text-align:right;
}
.td2
{
	text-align:left;
}
.btn{ background-color:#FFF; border:1px solid #CDCDCD;height:30px; width:70px;} 
</style>
<script type="text/javascript">
$(function(){
	 //保存数据表信息
	 $('#submit').click(function(){
		 var tabid=document.getElementById("tableid").value;
		 var proid=document.getElementById('projectid').value;
		 var proname=document.getElementById('projectname').value;
		 var datid=document.getElementById('dataid').value;
		 var name=document.getElementById('tabname').value;
		 var note=document.getElementById('note').value;
		 if(name=="")
		 {
			alert("未填写数据表名称！");
			return false;
		 }
		 var r=true;
		 var ary1=new Array();
		 $("[name='t1']").each(function(){
			 if(this.value==""){
				 r=false
				 alert("字段信息中字段名称不能为空")
				 return;
			 }
			 ary1.push(this.value);;
		 })
		 if(!r){return;}
		 var ary2=new Array();
		 $("[name='t2']").each(function(){
			 if(this.value==""){
				 r=false;
				 alert("字段信息中字段类别不能为空")
				 return  false;
			 }
			 ary2.push(this.value);;
		 })
		 if(!r){return;}
		 var ary3=new Array();
		 $("[name='t3']").each(function(){
			 ary3.push(this.value);;
		 })
		  var ary4=new Array();
		 $("[name='t4']").each(function(){
			 ary4.push(this.value);;
		 })
		  var ary5=new Array();
		 $("[name='t5']").each(function(){
			 ary5.push(this.value);;
		 })
		  var ary6=new Array();
		 $("[name='t6']").each(function(){
			 ary6.push(this.value);;
		 })
		  var ary7=new Array();
		 $("[name='t7']").each(function(){
			 ary7.push(this.value);;
		 })
		 $.ajax({
		  		type: "POST",
		        url: "/Data/tablesave",
		        data:"tabid="+tabid+"&proid="+proid+"&proname="+proname+"&name="+name+"&dataid="+datid+"&note="+note+"&t1="+ary1+
		        "&t2="+ary2+"&t3="+ary3+"&t4="+ary4+"&t5="+ary5+"&t6="+ary6+"&t7="+ary7,
		        success: function(msg){
		        	if(msg==0){
			        	if(tabid!=""){
		                	alert("修改"+name+"表信息成功！");
		                	window.location.href='/Data/tablelst?dataid='+datid+'&projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>';
			        	}
			        	else{
			        		alert("新增数据表信息成功！");
		                	window.location.href='/Data/tablelst?dataid='+datid+'&projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>';
			        	}
               	}
		        }
		 });
	 });
	
});
function addRow()
{
	var row=document.getElementById("fieldtable").rows.length;
	var newRow = document.getElementById("fieldtable").insertRow(row);
	//得到表的对象并插入一行，下面是插入了行以后，填充相应的列节点，如下面所示
    var oCell = newRow.insertCell(0);//插入列的节点
    oCell.innerHTML = "<input type='text' style='width:100px;height:28px;' name='t1'>";//列里面填充的值，innerHtml值列内的所有元素 
    oCell = newRow.insertCell(1);//插入列的节点
    oCell.innerHTML = "<input type='text' style='width:100px;height:28px;' name='t2'>";//列里面填充的值，innerHtml值列内的所有元素  
    oCell = newRow.insertCell(2);//插入列的节点
    oCell.innerHTML = "<input type='text' style='width:100px;height:28px;' name='t3'>";//列里面填充的值，innerHtml值列内的所有元素      
    oCell = newRow.insertCell(3);//插入列的节点
    oCell.innerHTML = "<select name='t4' style='width:100px;height:28px;'><option value='0'>否</option><option value='1'>是</option></select>";//列里面填充的值，innerHtml值列内的所有元素 
    oCell = newRow.insertCell(4);//插入列的节点
    oCell.innerHTML = "<select name='t5' style='width:100px;height:28px;'><option value='0'>否</option><option value='1'>是</option></select>";//列里面填充的值，innerHtml值列内的所有元素    
    oCell = newRow.insertCell(5);//插入列的节点
    oCell.innerHTML = "<select name='t6' style='width:120px;height:28px;'><option value='0'>否</option><option value='1'>是</option></select>";//列里面填充的值，innerHtml值列内的所有元素          
    oCell = newRow.insertCell(6);
    oCell.innerHTML = "<input type='text' style='width:150px;height:28px;margin-left:20px;' name='t7'> &nbsp;<a href='#' onclick='removeRow(this);'><img src='/images/tubiao_del.png' title='删除'></img></a>"; 
} 
function removeRow(src)
{
	var oRow = src.parentElement.parentElement;  //获取当前事件的父节点
	document.getElementById("fieldtable").deleteRow(oRow.rowIndex);  //删除当前列
} 
</script>
</head>
<body>
<div style="width:1520px;height:600px;">
 <?php require APPLICATION_PATH.'/views/scripts/adminlogin/head.phtml';?>  
<div style="float:left;">
  <?php require APPLICATION_PATH.'/views/scripts/adminlogin/left.phtml';?>         
</div>
<div class="clear:both;"></div>
<div style="float:left;background:#F0F8FF;width:87.4%;height:auto;" >
<table>
<tr>
<td height="30" >&nbsp;&nbsp;&nbsp;&nbsp;当前位置：<b>
<a href="/Data/tablelst?dataid=<?=$this->dataid?>&projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>"><?=$this->dataname?></a>--<?=$this->detail['Medi_TableName']==""?"添加数据表":$this->detail['Medi_TableName']?></b></td>
</tr>
</table>
<hr />
<br/>
<div style="font-size: 14px"> 
<input type="hidden" id="tableid" name="tableid" value="<?=$this->detail['Medi_TableID']?>"/>   
<input type="hidden" id="projectid" name="projectid" value="<?=$this->projectid?>"/>  
<input type="hidden" id="projectname" name="projectname" value="<?=$this->projectname?>"/>    
<input type="hidden" id="dataid" name="dataid" value="<?=$this->dataid?>"/>   
 <table class="mm" style="width:95%;">
 <tr>
 <td class="td" style="width:100px;">数据表名称&nbsp;</td>
 <td class="td2" colspan="3">&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" id="tabname" name="tabname" style="width:300px;height:28px;" value="<?=$this->detail['Medi_TableName']?>"/></td>
 </tr>
 <?php if($this->detail['Medi_TableName']!=""){?>
 <tr>
 <td class="td">编写人&nbsp;</td>
 <td class="td2">&nbsp;&nbsp;&nbsp;&nbsp;<?=$this->detail['Medi_TableCreatName']?></td>
 <td class="td">创建时间&nbsp;</td>
 <td class="td2">&nbsp;&nbsp;&nbsp;&nbsp;<?=$this->detail['Medi_TableCreatTime']?></td>
 </tr>
  <tr>
 <td class="td">最近修改人&nbsp;</td>
 <td class="td2">&nbsp;&nbsp;&nbsp;&nbsp;<?=$this->detail['Medi_TableUpdateName']?></td>
 <td class="td">最近修改时间&nbsp;</td>
 <td class="td2">&nbsp;&nbsp;&nbsp;&nbsp;<?=$this->detail['Medi_TableUpdateTime']?></td>
 </tr>
 <?php }?>
  <tr>
 <td class="td">数据表说明&nbsp;</td>
 <td colspan="3" class="td2">&nbsp;&nbsp;&nbsp;&nbsp;<textarea id="note" name="note" rows="2" cols="100"><?=$this->detail['Medi_TableNote']?></textarea></td>
 </tr>
  <tr>
 <td class="td">表内字段信息&nbsp;</td>
 <td colspan="3">
	 <table style="width:90%;margin-left:20px;" id="fieldtable">
	 <tr>
	 <td colspan="7" class="td2">&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" onclick="addRow()"><img src="/images/tubiao_add.png" alt="添加" /></a></td>
	 </tr>
	 <tr>
	 <td>字段名</td><td>字段类型</td><td>字段长度</td><td>标识</td><td>主键</td><td>是否允许空</td><td>说明</td>
	 </tr>
	 <?php if(isset($this->detail)){foreach ($this->fields as $fields ){?>
	 <tr>
	 <td><input type="text" style="width:100px;height:28px;" name="t1" value="<?=$fields['Medi_DataName']?>"/></td>
	 <td><input type="text" style="width:100px;height:28px;" name="t2" value="<?=$fields['Medi_DataType']?>"/></td>
	 <td><input type="text" style="width:100px;height:28px;" name="t3" value="<?=$fields['Medi_DataLength']?>"/></td>
	 <td><select name="t4" style="width:100px;height:28px;">
	 		<option value="1" <?php echo $fields['Medi_IsSign']==1?'selected':'';?>>是</option>
	 		<option value="0" <?php echo $fields['Medi_IsSign']==0?'selected':'';?>>否</option>
	 	</select></td>
	 <td><select name="t5" style="width:100px;height:28px;">
	 		<option value="1" <?php echo $fields['Medi_IsPrimary']==1?'selected':'';?>>是</option>
	 		<option value="0" <?php echo $fields['Medi_IsPrimary']==0?'selected':'';?>>否</option>
	 	</select></td>
	 <td><select name="t6" style="width:120px;height:28px;">
	 		<option value="1" <?php echo $fields['Medi_IsEmpty']==1?'selected':'';?>>是</option>
	 		<option value="0" <?php echo $fields['Medi_IsEmpty']==0?'selected':'';?>>否</option>
	 	</select></td>
	 <td><input type="text" style="width:150px;height:28px;margin-left:20px;" name="t7" value="<?=$fields['Medi_DataNote']?>"/>&nbsp;&nbsp;
	 <a href='#' onclick='removeRow(this);'><img src='/images/tubiao_del.png' title='删除'></img></a></td>
	 </tr>
	 <?php }}else{?>
	 <tr>
	 <td><input type="text" style="width:100px;height:28px;" name="t1" value=""/></td>
	 <td><input type="text" style="width:100px;height:28px;" name="t2" value=""/></td>
	 <td><input type="text" style="width:100px;height:28px;" name="t3" value=""/></td>
	 <td><select name="t4" style="width:100px;height:28px;">
	 		<option value="0">否</option>
	 		<option value="1">是</option>	 		
	 	</select></td>
	 <td><select name="t5" style="width:100px;height:28px;">
	 		<option value="0">否</option>
	 		<option value="1">是</option>
	 	</select></td>
	 <td><select name="t6" style="width:120px;height:28px;">
	 		<option value="0">否</option>
	 		<option value="1">是</option>
	 	</select></td>
	 <td><input type="text" style="width:150px;height:28px;margin-left:20px;" name="t7" value=""/>&nbsp;&nbsp;
	 <a href='#' onclick='removeRow(this);'><img src='/images/tubiao_del.png' title='删除'></img></a></td>
	 </tr>
	 <?php }?>
	 </table>
 </td>
 </tr>
 <tr>
 <td colspan="4"><input type="button" id="submit" class="btn" value="保存" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 <input type="button" class="btn" value="取消" onclick="window.location.href='/Data/tablelst?dataid=<?=$this->dataid?>&projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>';"></input>
 </td>
 </tr>
 </table> 
</div>
<div class="clear:both;"></div>
</div>
</div>
</body>
</html>
