<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/css/reset.css" type="text/css" rel="stylesheet" />
<link href="/css/admin.css" type="text/css" rel="stylesheet" />
<script src="/Javascript/jquery-1.9.1.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="/css/tab.css" />
<title>数据表列表</title>
<style type="text/css">
.btn2{ background-color:#FFF; border:1px solid #CDCDCD;height:30px; width:70px;} 
.btn3{ background-color:#FFF; border:1px solid #CDCDCD;height:30px; width:70px;display:block;line-height:30px;color:black;text-align:center;} 
</style>
<script type="text/javascript">
 function addnewtable()
 {
	 window.location.href="/Data/tableedit?dataid=<?=$this->id?>&projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>&edittype=0";
 }
</script> 
</head>
<body >
<div style="width:1520px;height:600px;">
 <?php require APPLICATION_PATH.'/views/scripts/adminlogin/head.phtml';?>  
<div style="float:left;">
  <?php require APPLICATION_PATH.'/views/scripts/adminlogin/left.phtml';?>         
</div>
<div class="clear:both;"></div>
<div style="float:left;background:#F0F8FF;width:87.4%;height:900px;" >
<table>
<tr>
<td height="30" >&nbsp;&nbsp;当前位置：<b><a href="/Data/datalst?projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>">数据库字典列表</a>--数据表列表</b></td>
</tr>
</table>
<hr />
<div style="width:985px;height:40px;line-height:40px;margin-left:50px;font-size:18px;font-weight:bold;color:#0B54AD;float:left">数据表列表(<?=$this->lbcount?>)</div>
<?php if($this->loginuser['Medi_Level']==1){?>
<div style="width:200px;margin-top:30px;height:30px;overflow:hidden;"><input class="btn" type="button" value="添加新数据表" onclick="addnewtable()"/></div>
<?php }?>
<br/><br/><br/><br/>
<div style="font-size: 14px">       
 <table class="mm" style="width:70%; margin:0 auto;">
  <tr>
  <th>数据表名称</th><th>编写人</th><th>更新时间</th><th>表的说明</th><th>操作</th>
  </tr>
  <?php foreach($this->tablelst as $table){?>
  <tr>
  <td><?=$table['Medi_TableName']?></td>
  <td><?=$table['Medi_TableCreatName']?></td>
  <td><?=$table['Medi_TableUpdateTime']?></td>
  <td><?=$table['Medi_TableNote']?></td>
 <td><a href="/Data/tablelook?id=<?=$table['Medi_TableID']?>&dataid=<?=$this->id?>&projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>">查看</a>
 <?php if($this->loginuser['Medi_Level']==1){?>&nbsp;&nbsp;&nbsp;&nbsp;
 <a href="/Data/tableedit?id=<?=$table['Medi_TableID']?>&dataid=<?=$this->id?>&projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>&edittype=1">编辑</a>
 <?php }?></td>
  </tr>
  <?php }?>
   </table> 
   <?php if ($this->lbcount>10){?>   
   <table style="height:40px;width:400px;float:right;margin-right:170px;margin-top:10px;">
   <tr>
   <td ><?=$this->cpage?>/<?=$this->spage?>页</td>
   <td>
   <input type='text' id='edit_page' style='width:40px;height:25px;' />&nbsp;
   <input type="button" id="jump" onclick="jumpto()" class="btn2" value="跳转" />
   </td>
   <td>
   <div style="float:left;height:30px; visibility:<?=$this->cpage==1?'collapse':''?>;">  
   <a id="up" class="btn3" href="/Data/tablelst?dataid=<?=$this->id?>&projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>&cpage=<?=($this->cpage-1)?>">上一页</a>&nbsp;
    </div>
    <div style="float:left;margin-left:20px;visibility:<?=$this->cpage==$this->spage?'collapse':''?>">
   <a id="down" class="btn3" href="/Data/tablelst?dataid=<?=$this->id?>&projectid=<?=$this->projectid?>&projectname=<?=$this->projectname?>&cpage=<?=($this->cpage+1)?>">下一页</a>
   </div>
   </td>
   </tr>
   </table>
   <?php }?>
  <div style="padding-top:10px;margin-left:200px;"><?=$this->result?></div>
</div>
<div class="clear:both;"></div>
</div>
</div>
</body>
</html>
