<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/css/reset.css" type="text/css" rel="stylesheet" />
<link href="/css/admin.css" type="text/css" rel="stylesheet" />
<script src="/Javascript/jquery-1.9.1.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="/css/tab.css" />
<title>项目管理列表</title>
<style type="text/css">
.td
{
	 text-align:right;
}
</style>
<script type="text/javascript">
function testurl()
{
 	window.open('/Api/apitesturl?testurl='+encodeURIComponent('<?=$this->apidetail['Medi_ApiTestUrl']?>'));
}
</script>
</head>
<body>
<div style="width:1520px;height:600px;">
 <?php require APPLICATION_PATH.'/views/scripts/adminlogin/head.phtml';?>  
<div style="float:left;">
  <?php require APPLICATION_PATH.'/views/scripts/adminlogin/left.phtml';?>         
</div>
<div class="clear:both;"></div>
<div style="float:left;background:#F0F8FF;width:87.4%;height:auto;" >
<table>
<tr>
<td height="30" >&nbsp;&nbsp;&nbsp;&nbsp;当前位置：<b><a href="/Api/apilst?interfaceid=<?=$this->interfaceid?>&projectid=<?=$this->projectid?>">接口列表</a>--<?=$this->apidetail['Medi_ApiName']?></b></td>
</tr>
</table>
<hr />
<br/>
<div style="font-size: 14px"> 
<form action="/Projects/projecteditsave?edittype=<?=$this->edittype?>" method="post">    
 <table class="mm" style="width:70%;">
 <tr>
 <td class="td">接口名称&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td><?=$this->apidetail['Medi_ApiName']?></td>
 <td class="td">所属模块&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td><?=$this->apidetail['Medi_ApiBelongs']?></td>
 </tr>
 <tr>
 <td class="td">编写人&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td><?=$this->apidetail['Medi_ApiCreateName']?></td>
 <td class="td">创建时间&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td><?=$this->apidetail['Medi_ApiCreateTime']?></td>
 </tr>
  <tr>
 <td class="td">修改人&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td><?=$this->apidetail['Medi_ApiUpdateName']?></td>
 <td class="td">修改时间&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td><?=$this->apidetail['Medi_ApiUpdateTime']?></td>
 </tr>
  <tr>
 <td class="td">接口作用&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td colspan="3"><?=$this->apidetail['Medi_ApiAction']?></td>
 </tr>
  <tr>
 <td class="td">接口实例地址&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td colspan="2"><?=$this->apidetail['Medi_ApiUrl']?></td>
 <td><input type="button" value="测试接口" class="btn" onclick="testurl();"/></td>
 </tr>
  <tr>
 <td class="td">支持格式&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td colspan="3"><?=$this->apidetail['Medi_ApiFormat']?></td>
 </tr>
  <tr>
 <td class="td">请求方式&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td colspan="3"><?=$this->apidetail['Medi_ApiRequest']?></td>
 </tr>
  <tr>
 <td class="td">请求参数&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td colspan="3">
 <?php if(count($this->parameterdata)>0){?>
 <table style="width:90%;margin-left:30px;">
 <tr>
 <td>参数名</td><td>类型</td><td>说明</td>
 </tr>
 <?php foreach ($this->parameterdata as $par1){?>
 <tr>
 <td><?=$par1['Medi_RequestName']?></td><td><?=$par1['Medi_RequestType']?></td><td><?=$par1['Medi_RequestInfo']?></td>
 </tr>
 <?php }?>
 </table>
 <?php }else{echo "无";}?>
 </td>
 </tr>
  <tr>
 <td class="td">返回结果&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td colspan="3"><div style="width:800px;height:100px;overflow-y:scroll"><?=$this->apidetail['Medi_ApiResult']?></div></td>
 </tr>
 <tr>
 <td class="td">通用返回数据说明&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td colspan="3">
 <?php if(count($this->universaldata)>0){?>
 <table style="width:90%;margin-left:30px;">
 <tr><td>返回值字段</td><td>类型</td><td>value值</td><td>说明</td></tr>
 <?php foreach($this->universaldata as $un){?>
 <tr><td><?=$un['Medi_CommonName']?></td><td><?=$un['Medi_CommonType']?></td><td><?=$un['Medi_CommonValue']?></td><td><?=$un['Medi_CommonInfo']?></td></tr>
 <?php }?>
 </table>
 <?php }else{echo "无";}?>
 </td>
 </tr>
 <tr>
 <td class="td">返回具体字段信息说明&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td colspan="3">
 <?php if(count($this->parameterdata2)>0){?>
 <table style="width:90%;margin-left:30px;">
 <tr><td>字段名</td><td>类型</td><td>说明</td></tr>
 <?php foreach($this->parameterdata2 as $par2){?>
 <tr> <td><?=$par2['Medi_RequestName']?></td><td><?=$par2['Medi_RequestType']?></td><td><?=$par2['Medi_RequestInfo']?></td></tr>
 <?php }?>
 </table>
 <?php }else{echo "无";}?>
 </td>
 </tr>
 <tr>
 <td colspan="4"><a class="btn" href="/Api/apilst?interfaceid=<?=$this->interfaceid?>&projectid=<?=$this->projectid?>" style="border:1px solid #C7C7C7;color:black;background:#F0F0F0">返回</a></td>
 </tr>
 </table> 
 </form>
  <div style="padding-top:10px;margin-left:200px;"><?=$this->result?></div>
</div>
<div class="clear:both;"></div>
</div>
</div>
</body>
</html>
