<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/css/reset.css" type="text/css" rel="stylesheet" />
<link href="/css/admin.css" type="text/css" rel="stylesheet" />
<script src="/Javascript/jquery-1.9.1.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="/css/tab.css" />
<title>接口列表</title>
<script type="text/javascript">
 function addnewapi()
 {
	 window.location.href="/Api/apiedit?edittype=0&interfaceid=<?=$this->interfaceid?>&projectid=<?=$this->projectid?>";
 }
 function apidel(id)
 {
	 if(confirm("确定要删除该接口吗？"))
	 {
		 $.ajax({
	         type: "POST",
	         url: "/Api/apidel",
	         data:"id="+id,
	         success: function(msg){
		         if(msg==0){
			         alert("删除接口成功！");
			         window.location.href="/Api/apilst?interfaceid=<?=$this->interfaceid?>&projectid=<?=$this->projectid?>";
		         }
	         }
		 });
	 }
 }
</script> 
<style type="text/css">
.btn2{ background-color:#FFF; border:1px solid #CDCDCD;height:28px; width:70px;}
</style>
</head>
<body >
<div style="width:1520px;height:600px;">
 <?php require APPLICATION_PATH.'/views/scripts/adminlogin/head.phtml';?>  
<div style="float:left;">
  <?php require APPLICATION_PATH.'/views/scripts/adminlogin/left.phtml';?>         
</div>
<div class="clear:both;"></div>
<div style="float:left;background:#F0F8FF;width:87.4%;height:auto;" >
<table style="margin-top:5px;">
<tr>
<td height="30" >&nbsp;&nbsp;当前位置：<b><a href="/Api/interfacelst?projectid=<?=$this->projectid?>">接口文档列表</a>--接口列表</b></td>
<td style="width:500px;text-align:right;">
<form action="/Api/apilst?interfaceid=<?=$this->interfaceid?>&projectid=<?=$this->projectid?>" method="post">
<?php if($this->loginuser['Medi_UserName']=="linshi"){?>
<select name="sel">
<?php foreach ($this->model as $m){ if($m['Medi_ApiBelongs']=="指南模块接口"){?>
<option value="<?=$m['Medi_ApiBelongs']?>" <?=$this->sel==$m['Medi_ApiBelongs']?"selected":""?>><?=$m['Medi_ApiBelongs']?></option><?php }}?></select>
<?php }else{?>
<select name="sel"><option value="0">接口所属模块</option>
<?php foreach ($this->model as $m){?>
<option value="<?=$m['Medi_ApiBelongs']?>" <?=$this->sel==$m['Medi_ApiBelongs']?"selected":""?>><?=$m['Medi_ApiBelongs']?></option><?php }?></select>
<?php }?>
&nbsp;
<input type="submit" name="submit" value="查询" class="btn2"></input></form></td>
</tr>
</table>
<hr />
<div style="width:985px;height:40px;line-height:40px;margin-left:50px;font-size:18px;font-weight:bold;color:#0B54AD;float:left">接口列表(<?=count($this->apilst)?>)</div>
<?php if($this->loginuser['Medi_Level']==1){?>
<div style="width:200px;margin-top:30px;height:30px;overflow:hidden;"><input class="btn" type="button" value="添加新接口" onclick="addnewapi()"/></div>
<?php }?>
<br/>
<div style="color:red;font-weight:bold;margin-left:40px;">使用接口须知：域名为meditool.cn的所有接口地址域名改为https://api.meditool.cn<br/>所有网页展示地址不变http://meditool.cn</div>
<br/>
<div style="font-size: 14px">       
 <table class="mm" style="width:70%; margin:0 auto;height:auto;">
  <tr>
  <th>接口名称</th><th>所属模块</th><th>编写人</th><th>更新时间</th><th>操作</th>
  </tr>
  <?php foreach($this->apilst as $api){?>
  <tr>
  <td><?=$api['Medi_ApiName']?></td>
  <td><?=$api['Medi_ApiBelongs']?></td>
  <td><?=$api['Medi_ApiCreateName']?></td>
  <td><?=$api['Medi_ApiUpdateTime']?></td>
 <td><a target="_blank" href="/Api/apilook?apiid=<?=$api['Medi_ApiID']?>&interfaceid=<?=$this->interfaceid?>&projectid=<?=$this->projectid?>" title="查看接口">查看</a>&nbsp;&nbsp;&nbsp;&nbsp;
<?php if($this->loginuser['Medi_Level']==1){?>
 <a href="/Api/apiedit?apiid=<?=$api['Medi_ApiID']?>&interfaceid=<?=$this->interfaceid?>&projectid=<?=$this->projectid?>&edittype=1" title="编辑接口">编辑</a>&nbsp;&nbsp;&nbsp;&nbsp;
 <a  style="cursor:pointer;" onclick="apidel(<?=$api['Medi_ApiID']?>)" title="删除接口">删除</a>
 <?php }?>
 </td>
  </tr>
  <?php }?>
   </table> 
  <div style="padding-top:10px;margin-left:200px;"><?=$this->result?></div>
</div>
<div class="clear:both;"></div>
</div>
</div>
</body>
</html>
