<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/css/reset.css" type="text/css" rel="stylesheet" />
<link href="/css/admin.css" type="text/css" rel="stylesheet" />
<script src="/Javascript/jquery-1.9.1.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="/css/tab.css" />
<title>接口文档列表</title>
<script type="text/javascript">
 function btnsel()
 {
	 var selname=document.getElementById('selname').value;
	 window.location.href="/Projects/projectlst?selname="+selname;
 }
</script> 
</head>
<body >
<div style="width:1520px;height:600px;">
 <?php require APPLICATION_PATH.'/views/scripts/adminlogin/head.phtml';?>  
<div style="float:left;">
  <?php require APPLICATION_PATH.'/views/scripts/adminlogin/left.phtml';?>         
</div>
<div class="clear:both;"></div>
<div style="float:left;background:#F0F8FF;width:87.4%;height:900px;" >
<table>
<tr>
<td height="30" >&nbsp;&nbsp;当前位置：<b><?=$this->projectname?>项目--接口文档列表</b></td>
</tr>
</table>
<hr />
<div style="width:985px;height:40px;line-height:40px;margin-left:50px;font-size:18px;font-weight:bold;color:#0B54AD;float:left">接口文档列表(<?=count($this->interfacelst)?>)</div>
<?php if($this->loginuser['Medi_Level']==1){?>
<div style="width:200px;margin-top:20px;height:30px;overflow:hidden;"><a class="btn" href="/Api/addinterface" value="添加新版本接口文档" style="border:1px solid #C7C7C7;color:black;background:#F0F0F0">添加新版本接口文档</a></div>
<?php }?>
<br/>
<div style="font-size: 14px">       
 <table class="mm" style="width:70%; margin:0 auto;">
  <tr>
  <th>接口文档名称</th><th>版本号</th><th>编写人</th><th>更新时间</th><th>操作</th>
  </tr>
  <?php foreach($this->interfacelst as $interface){?>
  <tr>
  <td><?=$interface['Medi_InterfaceName']?></td>
  <td><?=$interface['Medi_InterfaceVersion']?></td>
  <td><?=$interface['Medi_InterfaceCreateName']?></td>
  <td><?=$interface['Medi_InterfaceUpdateTime']?></td>
 <td><a href="/Api/apilst?interfaceid=<?=$interface['Medi_InterfaceID']?>&projectid=<?=$this->projectid?>">查看</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/Projects/competencedel?competenceid=<?=$interface['Medi_InterfaceID']?>">导出word</a></td>
  </tr>
  <?php }?>
   </table> 
  <div style="padding-top:10px;margin-left:200px;"><?=$this->result?></div>
</div>
<div class="clear:both;"></div>
</div>
</div>
</body>
</html>
